In [2]:
import numpy as np

# Define the 2x2 Hadamard matrix
H = np.array([[1, 1],
              [1, -1]]) / np.sqrt(2)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(H)

# Display results
print("Hadamard Matrix (H):")
print(H)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors (columns correspond to eigenvalues):")
print(eigenvectors)

# Verify eigenvalue equation H * v = λ * v
for i in range(len(eigenvalues)):
    print(f"\nVerification for eigenvalue {eigenvalues[i]}:")
    print("H @ eigenvector:", np.dot(H, eigenvectors[:, i]))
    print("λ * eigenvector:", eigenvalues[i] * eigenvectors[:, i])


Hadamard Matrix (H):
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Eigenvalues:
[ 1. -1.]

Eigenvectors (columns correspond to eigenvalues):
[[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]

Verification for eigenvalue 1.0:
H @ eigenvector: [0.92387953 0.38268343]
λ * eigenvector: [0.92387953 0.38268343]

Verification for eigenvalue -0.9999999999999999:
H @ eigenvector: [ 0.38268343 -0.92387953]
λ * eigenvector: [ 0.38268343 -0.92387953]


Hadamard Matrix (H):
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Eigenvalues (fractions):
[Fraction(1, 1), Fraction(-1, 1)]

Eigenvectors (fractions, columns correspond to eigenvalues):
Eigenvector 1: ['886/959', '305/797']
Eigenvector 2: ['-305/797', '886/959']

Verification:
Verification for eigenvalue 1:
H @ eigenvector: [Fraction(886, 959), Fraction(305, 797)]
λ * eigenvector: [Fraction(886, 959), Fraction(305, 797)]
Verification for eigenvalue -1:
H @ eigenvector: [Fraction(305, 797), Fraction(-886, 959)]
λ * eigenvector: [Fraction(305, 797), Fraction(-886, 959)]
