In [2]:
import numpy as np

def is_diagonalizable(matrix):
    """
    Checks if a matrix is diagonalizable.
    """
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    # Check if the eigenvectors form a linearly independent set
    return np.linalg.matrix_rank(eigenvectors) == matrix.shape[0]

def diagonalize_matrix(matrix):
    """
    Attempts to diagonalize a matrix.
    Returns the diagonal matrix and the transformation matrix if successful.
    Raises an error if the matrix is not diagonalizable.
    """
    if not is_diagonalizable(matrix):
        raise ValueError("The matrix is not diagonalizable.")
    
    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    # Form the diagonal matrix
    diagonal_matrix = np.diag(eigenvalues)
    return diagonal_matrix, eigenvectors

# Example Usage
A = np.array([[5, 4, 2],
              [0, 1, 0],
              [0, 0, 3]])

try:
    D, P = diagonalize_matrix(A)
    print("Diagonal matrix D:")
    print(D)
    print("Transformation matrix P:")
    print(P)
    print("Verification (P^-1 A P):")
    print(np.linalg.inv(P) @ A @ P)
except ValueError as e:
    print(e)


Diagonal matrix D:
[[5. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]
Transformation matrix P:
[[ 1.         -0.70710678 -0.70710678]
 [ 0.          0.70710678  0.        ]
 [ 0.          0.          0.70710678]]
Verification (P^-1 A P):
[[5. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]
