In [2]:
import numpy as np

# Define the matrices
# matrix1 = np.array([[1.0, 0.0], [0.0, -1.0]])
# matrix2 = np.array([[0.0, 1.0], [1.0, 0.0]])
matrix1 = np.array([[1.0, 0.0], [0.0, -1.0]])
matrix2 = np.array([[0.0, 1.0], [1.0, 0.0]])

# Compute the tensor product
tensor_product = np.kron(matrix1, matrix1)

# Display the result
print("Tensor product of matrix1 and matrix2:")
print(tensor_product)

Tensor product of matrix1 and matrix2:
[[ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]
 [ 0.  0. -1. -0.]
 [ 0. -0. -0.  1.]]


In [3]:
2 + matrix1

array([[3., 2.],
       [2., 1.]])

In [5]:
matrix1 - 2

array([[-1., -2.],
       [-2., -3.]])