In [5]:
from plyfile import PlyData
import numpy as np

def read_ply(filename):
    """Reads a PLY file and returns the x, y, and z coordinates as a NumPy array."""
    plydata = PlyData.read(filename)
    # Access the first element (vertices) directly
    vertices = plydata['vertex']
    x = vertices['x']
    y = vertices['y']
    z = vertices['z']
    return np.column_stack((x, y, z))

In [8]:
coors = read_ply("points0.ply")
print(coors)
print(coors.size)

[[-1.1682616e-02  3.2226269e+00 -7.1690440e+00]
 [ 3.0156495e-02  3.2942004e+00 -7.0903602e+00]
 [-5.0173581e-02  3.2012017e+00 -7.1605921e+00]
 ...
 [ 4.9901471e-01 -1.8212005e+00 -1.2231232e+01]
 [ 4.9184832e-01 -1.7516638e+00 -1.2238552e+01]
 [ 4.9593040e-01 -1.8855141e+00 -1.2452033e+01]]
375513
